# Default values for Morpheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

worker:
  type: daemonSet
  replicaCount: 0
  maxSkew: 1

image:
  repository: monadicalsas/morpheus
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 80
workerMonitorService:
  type: ClusterIP
  port: 80
container:
  port: 8001

domain: https://morpheus.monadical.io

imagePullSecrets:
  - name: regcred
