{
 "title": "Serve Dashboard",
 "tags": [ "rayVersion:2.8.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Application",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{ray_instance_name=\"$instanceName\",}, application)"
    }
   },
   {
    "name": "HTTP_Route",
    "label": "HTTP Route",
    "query": {
     "query": "label_values(ray_serve_num_http_requests{ray_instance_name=\"$instanceName\",}, route)"
    }
   },
   {
    "name": "gRPC_Method",
    "label": "gRPC Service Method",
    "query": {
     "query": "label_values(ray_serve_num_grpc_requests{ray_instance_name=\"$instanceName\",}, method)"
    }
   },
   {
    "name": "instanceName",
    "query": {
     "query": "label_values(ray_instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Utilization",
   "type": "graph",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster. Ignores application variable.",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{ray_instance_name=\"$instanceName\",})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{}) / on() (sum(autoscaler_cluster_resources{resource='GPU',ray_instance_name=\"$instanceName\",}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{}) / on() (sum(ray_node_mem_total{ray_instance_name=\"$instanceName\",})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{}) / on() (sum(ray_node_gram_available{ray_instance_name=\"$instanceName\",}) + sum(ray_node_gram_used{ray_instance_name=\"$instanceName\",})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{ray_instance_name=\"$instanceName\",}) / on() sum(ray_resources{Name=\"object_store_memory\",ray_instance_name=\"$instanceName\",}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{ray_instance_name=\"$instanceName\",}) / on() (sum(ray_node_disk_free{ray_instance_name=\"$instanceName\",}) + sum(ray_node_disk_usage{ray_instance_name=\"$instanceName\",})) * 100",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "QPS per application",
   "type": "graph",
   "description": "QPS for each selected application.",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_requests{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_instance_name=\"$instanceName\",}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_requests{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_instance_name=\"$instanceName\",}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "Error QPS per application",
   "type": "graph",
   "description": "Error QPS for each selected application.",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_error_requests{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_instance_name=\"$instanceName\",}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_error_requests{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_instance_name=\"$instanceName\",}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "Replicas per deployment",
   "type": "graph",
   "description": "Number of replicas per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{ray_instance_name=\"$instanceName\",}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "QPS per deployment",
   "type": "graph",
   "description": "QPS for each deployment.",
   "gridPos": { "x": 8, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter{application=~\"$Application\",application!~\"\",ray_instance_name=\"$instanceName\",}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Error QPS per deployment",
   "type": "graph",
   "description": "Error QPS for each deplyoment.",
   "gridPos": { "x": 16, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter{application=~\"$Application\",application!~\"\",ray_instance_name=\"$instanceName\"}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "graph",
   "description": "Number of requests queued per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{ray_instance_name=\"$instanceName\",}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "description": "Number of nodes in this cluster. Ignores \"Application\" variable.",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_active_nodes{ray_instance_name=\"$instanceName\",}) by (NodeType)",
     "legendFormat": "Active Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_recently_failed_nodes{ray_instance_name=\"$instanceName\",}) by (NodeType)",
     "legendFormat": "Failed Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_pending_nodes{ray_instance_name=\"$instanceName\",}) by (NodeType)",
     "legendFormat": "Pending Nodes: {{NodeType}}"
    }
   ]
  },
  {
   "title": "Node network",
   "type": "graph",
   "description": "Network speed per node. Ignores \"Application\" variable.",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_network_receive_speed{ray_instance_name=\"$instanceName\",}) by (instance)",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "sum(ray_node_network_send_speed{ray_instance_name=\"$instanceName\",}) by (instance)",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  }
 ]
}