---
samplers:
  - id: "EulerDiscreteScheduler"
    name: "Euler"
    description: "Euler "
  - id: "EulerAncestralDiscreteScheduler"
    name: "Euler a"
    description: "Euler ancestral"
  - id: "KDPM2DiscreteScheduler"
    name: "DPM2"
    description: "DPM Discrete"
  - id: "LMSDiscreteScheduler"
    name: "LMS"
    description: "Linear multistep"
  - id: "HeunDiscreteScheduler"
    name: "Heun"
    description: "Heun"
  - id: "KDPM2AncestralDiscreteScheduler"
    name: "DPM2 a"
    description: "DPM Discrete Scheduler with ancestral sampling"
  - id: "DDPMScheduler"
    name: "DDPM"
    description: "Denoising diffusion probabilistic models"
  - id: "DPMSolverMultistepScheduler"
    name: "DPM++ 2M"
    description: "Multistep DPM-Solver"
  - id: "DDIMScheduler"
    name: "DDIM"
    description: "Denoising diffusion implicit models"
  - id: "DPMSolverSinglestepScheduler"
    name: "DPM"
    description: "Singlestep DPM"
  - id: "DEISMultistepScheduler"
    name: "DEIS"
    description: "Fast Sampling of Diffusion Models with Exponential Integrator."
  - id: "UniPCMultistepScheduler"
    name: "UniPC"
    description: "UniPC is a training-free framework designed for the fast sampling of diffusion models, which consists of a corrector (UniC) and a predictor (UniP) that share a unified analytical form and support arbitrary orders."
  - id: "PNDMScheduler"
    name: "PNDM"
    description: "Pseudo numerical methods for diffusion models (PNDM)"


