"""add upscaling option field in SDmodel

Revision ID: 27dddc20ef29
Revises: cd0b4780c076
Create Date: 2023-07-14 17:29:07.725260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27dddc20ef29'
down_revision = 'cd0b4780c076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdmodel', sa.Column('upscaling', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdmodel', 'upscaling')
    # ### end Alembic commands ###
