"""add is_new_user parameter
Revision ID: 7592af049bd2
Revises: 27dddc20ef29
Create Date: 2023-08-23 19:57:23.107454
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7592af049bd2'
down_revision = '27dddc20ef29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_new_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_new_user')
    # ### end Alembic commands ###