"""add color palette

Revision ID: 2b5369a1278f
Revises: ff9030a4288b
Create Date: 2023-11-30 18:50:59.518534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5369a1278f'
down_revision = 'ff9030a4288b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('palette_technique', sa.String(length=64), nullable=True))
    op.add_column('prompt', sa.Column('controlnet_model', sa.String(length=64), nullable=True))
    op.add_column('prompt', sa.Column('controlnet_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt', 'controlnet_type')
    op.drop_column('prompt', 'controlnet_model')
    op.drop_column('prompt', 'palette_technique')
    # ### end Alembic commands ###
