"""add color palette

Revision ID: f512974ad280
Revises: ff9030a4288b
Create Date: 2023-12-01 04:51:43.073644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f512974ad280'
down_revision = 'ff9030a4288b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('palette_technique', sa.String(length=64), nullable=True))
    op.add_column('prompt', sa.Column('controlnet_model', sa.String(length=64), nullable=True))
    op.add_column('prompt', sa.Column('controlnet_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt', 'controlnet_type')
    op.drop_column('prompt', 'controlnet_model')
    op.drop_column('prompt', 'palette_technique')
    # ### end Alembic commands ###
