# Default values for Morpheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: monadicalsas/morpheus-worker
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "worker-ray-latest"

worker:
  headNodeSelector: "worker-head"
  nodeSelector: "gpu-adv"
  rayVersion: 2.7.0
  head:
    rayStartParams:
      numCpus: "3"
      numGpus: "0"
    resources:
      limits:
        cpu: "3"
        memory: "13G"
  workerGroup:
    replicas: 2
    minReplicas: 2
    maxReplicas: 6
    rayStartParams:
      numCpus: "3"
      numGpus: "1"
    resources:
      limits:
        cpu: "3"
        memory: "10G"
        gpu: 1

imagePullSecrets:
  - name: regcred
