{{ if eq .Values.worker.type "daemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: morpheus-worker-prompt
  labels:
    name: morpheus-worker-prompt
spec:
  selector:
    matchLabels:
      name: morpheus-worker-prompt
  template:
    metadata:
      labels:
        name: morpheus-worker-prompt
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-worker-prompt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - app.celery.workers.magic_prompt_app
            - worker
            - --max-tasks-per-child=1
            - --loglevel=info
            - --concurrency=1
            - -Q
            - magic_prompt
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: POSTGRES_USER
                optional: false
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: POSTGRES_DB
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: POSTGRES_PASSWORD
                optional: false
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: POSTGRES_HOST
                optional: false
          - name: FIREBASE_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: FIREBASE_PROJECT_ID
                optional: true
          - name: FIREBASE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: FIREBASE_PRIVATE_KEY
                optional: true
          - name: FIREBASE_WEB_API_KEY
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: FIREBASE_WEB_API_KEY
                optional: true
          - name: FIREBASE_CLIENT_EMAIL
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: FIREBASE_CLIENT_EMAIL
                optional: true
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: AWS_ACCESS_KEY_ID
                optional: true
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: AWS_SECRET_ACCESS_KEY
                optional: true
          - name: IMAGES_BUCKET
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: IMAGES_BUCKET
                optional: true
          - name: IMAGES_TEMP_BUCKET
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: IMAGES_TEMP_BUCKET
                optional: true
          - name: MODELS_BUCKET
            valueFrom:
              secretKeyRef:
                name: morpheus-secret
                key: MODELS_BUCKET
                optional: true
          - name: ALLOWED_ORIGINS
            value: {{ .Values.domain }}
          - name: CELERY_BROKER_URL
            value: redis://redis:6379/0
          - name: CELERY_RESULT_BACKEND
            value: redis://redis:6379/0
          - name: ENVIRONMENT
            value: prod
          volumeMounts:
          - name: models
            mountPath: /mnt
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-claim
          readOnly: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: morpheus-type
                operator: In
                values:
                - gpu
{{ end }}
