apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus-worker-cloudwatch-monitor
  labels:
    name: morpheus-worker-cloudwatch-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: morpheus-worker-cloudwatch-monitor
  template:
    metadata:
      labels:
        name: morpheus-worker-cloudwatch-monitor
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-cw-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python3
            - monitor/cloudwatch-ray.py
          env:
          - name: ENVIRONMENT
            value: prod
          - name: CLOUDWATCH_REGION
            valueFrom:
              secretKeyRef:
                key: CLOUDWATCH_REGION
                name: morpheus-secret
                optional: true
          - name: CLOUDWATCH_NAMESPACE
            valueFrom:
              secretKeyRef:
                key: CLOUDWATCH_NAMESPACE
                name: morpheus-secret
                optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: morpheus-type
                operator: In
                values:
                - web
