apiVersion: v1
kind: Service
metadata:
  name: worker-monitor
  labels:
    name: worker-monitor
spec:
  type: {{ .Values.workerMonitorService.type }}
  ports:
    - port: {{ .Values.workerMonitorService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: morpheus-worker-monitor
