apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    name: redis
