global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
# Scrape from each Ray node as defined in the service_discovery.json provided by Ray.
- job_name: 'morpheus'
  http_sd_configs:
    - url: http://worker-ray:8000/get-prometheus-sd-file
remote_write:
- url: 'https://prometheus-morpheus.com/api/v1/write'
  basic_auth:
    username: "user"
    password: "password"
