name: CI Test and deploy Collaborative
on:
  workflow_dispatch:
  workflow_call:
env:
  MAX_LINE_LENGTH: 120
  WORKING_DIR_BACKEND: morpheus-collaborative
  MORPHEUS_COLLABORATIVE_IMAGE_NAME: ${{ env.MORPHEUS_COLLABORATIVE_IMAGE_NAME_REPOSITORY || 'monadicalsas/morpheus-collaborative' }}
jobs:
  ci-collab:
    uses: ./.github/workflows/ci-collaborative.yaml
    with:
      called: true
    secrets: inherit
  deploy-collaborative-k8s:
    runs-on: ubuntu-latest
    needs:
      - ci-collab
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create kube config
        run: |
          aws eks --region ${{secrets.AWS_REGION}} update-kubeconfig --name ${{secrets.AWS_CLUSTER_NAME}}
      - name: Deploy using helm
        run: |
          helm upgrade --timeout 15m0s --install --atomic morpheus-collaborative ./morpheus-collaborative/helm/charts/morpheus-collaborative/ \
            --set image.tag=${{ github.run_id }} --set domain=${{secrets.FRONTEND_DOMAIN}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push Docker Image
        run: |
          docker pull ${{ env.MORPHEUS_COLLABORATIVE_IMAGE_NAME }}:${{ github.run_id }}
          docker tag ${{ env.MORPHEUS_COLLABORATIVE_IMAGE_NAME }}:${{ github.run_id }} ${{ env.MORPHEUS_COLLABORATIVE_IMAGE_NAME }}:latest
          docker push ${{ env.MORPHEUS_COLLABORATIVE_IMAGE_NAME }}:latest
