name: CI Test and deploy Frontend
on:
  workflow_dispatch:
  workflow_call:
jobs:
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yaml
    with:
      called: true
    secrets: inherit
  deploy-frontend-k8s:
    runs-on: ubuntu-latest
    needs:
      - ci-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create kube config
        run: |
          aws eks --region ${{secrets.AWS_REGION}} update-kubeconfig --name ${{secrets.AWS_CLUSTER_NAME}}
      - name: Deploy using helm
        run: |
          helm upgrade --timeout 15m0s --install --atomic morpheus-client ./morpheus-client/helm/charts/morpheus-client/ \
            --set image.tag=client-${{ github.run_id }}
      - name: Clear cache in cloudflare
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{secrets.CLOUDFLARE_ZONE_ID}}/purge_cache" \
          -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}' || echo "Failed to clear caches"
