name: CD worker ray base
on:
  workflow_dispatch:
env:
  WORKING_DIR: morpheus-worker
  MORPHEUS_WORKER_IMAGE_NAME: ${{ vars.MORPHEUS_WORKER_IMAGE_NAME_REPOSITORY || 'monadicalsas/morpheus-worker' }}
jobs:
  ci-worker-ray:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v2
      - name: Run echo
        run: |
          echo "Running worker ray cd process"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:morpheus-worker"
          file: "Dockerfile.base"
          platforms: |
            linux/arm64
            linux/amd64
          push: true
          tags: ${{ env.MORPHEUS_WORKER_IMAGE_NAME }}:base
