name: CI Test and deploy Worker Ray
on:
  workflow_dispatch:
  workflow_call:
env:
  WORKING_DIR_BACKEND: morpheus-worker/ray
  MORPHEUS_WORKER_IMAGE_NAME: ${{ vars.MORPHEUS_WORKER_IMAGE_NAME_REPOSITORY || 'monadicalsas/morpheus-worker' }}
jobs:
  ci-worker-ray:
    uses: ./.github/workflows/ci-worker-ray.yaml
    with:
      called: true
    secrets: inherit
  deploy-worker-ray-k8s:
    runs-on: ubuntu-latest
    needs:
      - ci-worker-ray
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create kube config
        run: |
          aws eks --region ${{secrets.AWS_REGION}} update-kubeconfig --name ${{secrets.AWS_CLUSTER_NAME}}
          helm upgrade --timeout 15m0s --install --atomic morpheus-worker-ray ./morpheus-worker/ray/helm/charts/morpheus-worker-ray/ \
            --set image.tag=${{ github.run_id }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push Docker Image
        run: |
          docker pull ${{ env.MORPHEUS_WORKER_IMAGE_NAME }}:${{ github.run_id }}
          docker tag ${{ env.MORPHEUS_WORKER_IMAGE_NAME }}:${{ github.run_id }} ${{ env.MORPHEUS_WORKER_IMAGE_NAME }}:latest
          docker push ${{ env.MORPHEUS_WORKER_IMAGE_NAME }}:latest
