name: CI data library
on:
  workflow_call:
    inputs:
      called:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      called:
        required: false
        type: string
env:
  MAX_LINE_LENGTH: 120
  WORKING_DIR: morpheus-data
  MORPHEUS_DATA_IMAGE_NAME: ${{ vars.MORPHEUS_DATA_IMAGE_NAME_REPOSITORY || 'monadicalsas/morpheus-data' }}
jobs:
  linters:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        id: python-cache
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: ./${{ env.WORKING_DIR }}/requirements.lint.txt
      - name: Install packages
        run: |
          pip install -r requirements.lint.txt
      - name: Black
        run: |
          black --line-length $MAX_LINE_LENGTH --exclude morpheus_data/migrations/ .
      - name: Flake8
        run: |
          flake8 --max-line-length $MAX_LINE_LENGTH --exclude morpheus_data/migrations/ .
  ci-data-library:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        if: ${{ inputs.called == 'true' }}
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        if: ${{ inputs.called == 'true' }}
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: ${{ inputs.called == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        if: ${{ inputs.called == 'true' }}
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:morpheus-data"
          build-args: |
            BUILD_ENV=copy
          push: true
          tags: ${{ env.MORPHEUS_DATA_IMAGE_NAME }}:latest
