name: CI worker ray
on:
  workflow_call:
    inputs:
      called:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      called:
        required: false
        type: string
env:
  WORKING_DIR: morpheus-worker
  MORPHEUS_WORKER_IMAGE_NAME: ${{ vars.MORPHEUS_WORKER_IMAGE_NAME_REPOSITORY || 'monadicalsas/morpheus-worker' }}
jobs:
  ci-worker-ray:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true
      - uses: actions/checkout@v2
      - name: Run echo
        run: |
          echo "Running worker ray ci process"
      -
        name: Set up QEMU
        if: ${{ inputs.called == 'true' }}
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        if: ${{ inputs.called == 'true' }}
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: ${{ inputs.called == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        if: ${{ inputs.called == 'true' }}
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:morpheus-worker/ray"
          push: true
          tags: ${{ env.MORPHEUS_WORKER_IMAGE_NAME }}:${{ github.run_id }}
